simple_ecommerce/profile/urls.py
from django.urls import path

from . import views

app_name = 'profile'

urlpatterns = [
    path('profile/<str:email>/private/', views.private, name='private'),
    path('profile/<str:email>/public-store/', views.public, name='public'),
    path('high-air/', views.high_air, name='high_air')
]

simple_ecommerce/shop/urls.py
from django.urls import path

from . import views

app_name = 'shop'

urlpatterns = [
    path('api/products/', views.get_many, name='get_many'),
    path('api/products/<int:product_id>/', views.fetch_or_delete, name='fetch_or_delete'),
    path('api/products/create/', views.create, name='create'),

    # only for testing purposes
    path('api/register_partner/', views.register, name='register'),

    path('shop/products/list/', views.list_products, name='list_products'),
    path('shop/products/<int:product_id>/', views.get_product, name='get_product'),
    path('shop/basket/add/', views.add_to_cart, name='add_to_cart'),
    path('shop/basket/', views.show_basket, name='show_current_basket'),
    path('shop/basket/<int:order_id>/', views.show_basket, name='show_basket'),
    path('shop/basket/delete/<int:cart_item_id>/', views.delete_from_basket, name='delete_from_basket'),
    path('shop/checkout/<int:order_id>/', views.checkout, name='checkout'),

]

simple_ecommerce/simple_ecommerce/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('', include('user_mgmt.urls')),
    path('', include('shop.urls')),
    path('', include('profile.urls'))
]

# register static files base
urlpatterns += staticfiles_urlpatterns()

simple_ecommerce/user_mgmt/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [
    path('index/', views.index, name='index'),
    path('accounts/login/', LoginView.as_view(template_name='user_mgmt/login.html'), name='login'),
    path('accounts/logout/', views.logout_view, name='logout'),
    path('accounts/registration/', views.registration_view, name='registration'),
    path('accounts/<str:email>/verify/<str:token>/', views.verify, name='verify'),

    path('accounts/password-reset/', views.password_forgotten, name='password_forgotten'),
    path('accounts/<str:email>/reset/<str:token>/', views.reset_password, name='reset_password'),

    path('accounts/tokensignin/', views.token_sign_in, name='tokensignin')
]

simple_ecommerce/simple_ecommerce/views.py
from django.shortcuts import redirect
from django.urls import reverse
from django.views.decorators.http import require_GET


@require_GET
def index(request):
    return redirect(reverse('accounts:index'))

simple_ecommerce/simple_ecommerce/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="author" content="Moritz Wilhelm; Daniel Emmel">
    <meta name="google-signin-client_id"
          content="39346139449-nrl3aj1sc0cijkbpg4h0prtgbmb8trs1.apps.googleusercontent.com">
    <title>Official Speedwagon Foundation Shop</title>
    {% load static %}
    <link rel="shortcut icon" type="image/png" href="{% static 'img/Pillar_Men.ico' %}"/>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
          integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
            integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
            integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
            integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
            crossorigin="anonymous"></script>
    <script src="https://apis.google.com/js/platform.js" async defer></script>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light border">
    <a class="navbar-brand">SFS</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        {% if not user.is_authenticated %}
            <ul class="navbar-nav mr-auto">
                <li class="nav-item{% if 'login' in request.path %} active{% endif %}">
                    <a class="nav-link" href="{% url 'accounts:login' %}">
                        Login
                    </a>
                </li>
                <li class="nav-item {% if 'registration' in request.path %} active{% endif %}">
                    <a class="nav-link" href="{% url 'accounts:registration' %}">
                        Registration
                    </a>
                </li>
            </ul>
        {% else %}
            <ul class="navbar-nav mr-auto">
                <li class="nav-item{% if 'index' in request.path %} active{% endif %}">
                    <a class="nav-link" href="{% url 'accounts:index' %}">
                        Home
                    </a>
                </li>
                <li class="nav-item{% if 'products' in request.path %} active{% endif %}">
                    <a class="nav-link" href="{% url 'shop:list_products' %}">
                        Shop
                    </a>
                </li>
                <li class="nav-item{% if 'basket' in request.path %} active{% endif %}">
                    <a class="nav-link" href="{% url 'shop:show_current_basket' %}">
                        My Basket
                    </a>
                </li>
                 <li class="nav-item{% if 'private' in request.path %} active{% endif %}">
                    <a class="nav-link" href="{% url 'profile:private' user.username %}">
                        Private Profile
                    </a>
                </li>
            <li class="nav-item{% if 'public' in request.path %} active{% endif %}">
                    <a class="nav-link" href="{% url 'profile:public' user.username %}">
                        Public Profile
                    </a>
                </li>
            </ul>
            <form action="{% url 'accounts:logout' %}" method="post">
                {% csrf_token %}
                {% load colorful_style %}
                <button type="submit" class="btn" style="{% colorful_style%}" onclick="gapi.auth2.getAuthInstance().signOut()">Logout
                </button>
            </form>
            <script>
                window.onload = function () {
                    gapi.load('auth2', function () {
                        gapi.auth2.init()
                    });
                }
            </script>
        {% endif %}
    </div>
</nav>
<br>
<div class="container-fluid">
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
                {{ message|linebreaksbr }}
            </div>
        {% endfor %}
    {% endif %}
    {% block content %}
    {% endblock %}
</div>
</body>
</html>

simple_ecommerce/simple_ecommerce/templates/high_air.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>High-Air App</title>
</head>
{% load colorful_style %}
<body>
<h1 style="{% colorful_style %}">Very high</h1>
<script async src='https://www.google-analytics.com/analytics.js'></script>
<script>
    window.addEventListener('message', function (event) {
        if (!/^http:\/\/(localhost|127.0.0.1):3000$/.test(event.origin))
            return
        // Create a tracker and store the client id
        ga('create', 'UA-XXXXX-Y', 'auto', {
            clientId: event.data
        });
    });
</script>
</body>
</html>