simple_ecommerce/shop/urls.py
from django.urls import path

from . import views

app_name = 'shop'

urlpatterns = [
    path('api/products/', views.get_many, name='get_many'),
    path('api/products/<int:product_id>/', views.fetch_or_delete, name='fetch_or_delete'),
    path('api/products/create/', views.create, name='create'),

    # only for testing purposes
    path('api/register_partner/', views.register, name='register'),

    path('shop/products/list/', views.list_products, name='list_products'),
    path('shop/products/<int:product_id>/', views.get_product, name='get_product'),
    path('shop/basket/add/', views.add_to_cart, name='add_to_cart'),
    path('shop/basket/', views.show_basket, name='show_current_basket'),
    path('shop/basket/<int:order_id>/', views.show_basket, name='show_basket'),
    path('shop/basket/delete/<int:cart_item_id>/', views.delete_from_basket, name='delete_from_basket'),
    path('shop/checkout/<int:order_id>/', views.checkout, name='checkout'),

]

simple_ecommerce/simple_ecommerce/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('', include('user_mgmt.urls')),
    path('', include('shop.urls')),
    path('', include('profile.urls'))
]

# register static files base
urlpatterns += staticfiles_urlpatterns()

simple_ecommerce/shop/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from user_mgmt.models import User


class Partner(models.Model):
    name = models.CharField(max_length=30)
    web_site = models.URLField()
    token = models.CharField(_('token'), max_length=128, unique=True)


class Product(models.Model):
    name = models.CharField(max_length=30)
    description = models.TextField()
    slug = models.SlugField()
    price = models.FloatField()
    special_price = models.FloatField()
    count = models.IntegerField()
    image = models.URLField()
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, default=None)
    partner = models.ForeignKey(Partner, on_delete=models.CASCADE, null=True, default=None)


class Payment(models.Model):
    amount = models.FloatField()
    method = models.CharField(max_length=30)


class Address(models.Model):
    user = models.ManyToManyField(User)
    street = models.CharField(max_length=200)
    city = models.CharField(max_length=200)
    zip_code = models.IntegerField()
    country = models.CharField(max_length=200)
    additional_info = models.CharField(max_length=200)


class Order(models.Model):
    customer_id = models.ForeignKey(User, on_delete=models.CASCADE)
    placed = models.BooleanField(default=False)
    date_placed = models.DateTimeField(null=True)
    shipping_address = models.ForeignKey(Address, on_delete=models.CASCADE, null=True)
    payment = models.ForeignKey(Payment, on_delete=models.CASCADE, null=True)


class CartItem(models.Model):
    product_id = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=0)
    order_id = models.ForeignKey(Order, on_delete=models.CASCADE)

    @property
    def total_cost(self):
        return self.quantity * self.product_id.price

simple_ecommerce/shop/views.py
import json
from re import match
from urllib.parse import unquote

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.hashers import make_password, check_password
from django.db import IntegrityError
from django.db.models import Q
from django.forms import model_to_dict
from django.http import HttpResponse, JsonResponse, Http404
from django.shortcuts import render, redirect
from django.urls import reverse
from django.utils import timezone
from django.utils.crypto import get_random_string
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST, require_GET, require_http_methods

from shop.models import Partner, Product, Order, CartItem, Address, Payment


def _get_partner(request):
    bearer_token = request.headers.get('Authorization', '')
    if match(r'Bearer [a-zA-Z0-9]{16}$', bearer_token) is None:
        raise Partner.DoesNotExist
    token = bearer_token.split()[1]

    for partner in Partner.objects.all():
        if check_password(token, partner.token):
            return partner
    else:
        raise Partner.DoesNotExist


@csrf_exempt
@never_cache
@require_GET
def get_many(request):
    try:
        partner = _get_partner(request)
    except Partner.DoesNotExist:
        return HttpResponse(status=400)

    try:
        page = int(request.GET.get('page'))
        pagination = int(request.GET.get('pagination'))
    except ValueError:
        return HttpResponse(status=400)
    except TypeError:
        results = Product.objects.filter(Q(partner=partner) | Q(partner=None, user=None))
    else:
        start = (page - 1) * pagination
        end = start + pagination
        try:
            results = Product.objects.filter(Q(partner=partner) | Q(partner=None, user=None)).order_by('id')[start:end]
        except AssertionError:
            return HttpResponse(status=400)
    return JsonResponse({'result': [model_to_dict(result) for result in results]}, json_dumps_params={'indent': 2})


@csrf_exempt
@never_cache
@require_http_methods(['GET', 'DELETE'])
def fetch_or_delete(request, product_id):
    try:
        partner = _get_partner(request)
    except Partner.DoesNotExist:
        return HttpResponse(status=400)

    product = Product.objects.filter(Q(partner=partner, id=product_id) | Q(partner=None, user=None, id=product_id))
    if not product.exists():
        raise Http404
    if request.method == 'GET':
        return JsonResponse({'result': model_to_dict(product.first())}, json_dumps_params={'indent': 2})
    else:
        product.first().delete()
        return HttpResponse(status=200)


@csrf_exempt
@require_POST
def create(request):
    try:
        partner = _get_partner(request)
    except Partner.DoesNotExist:
        return HttpResponse(status=400)

    values = json.loads(request.body)

    try:
        name = values['name']
        description = values['description']
        price = round(float(values['price']), 2)
        special_price = round(float(values['special_price']), 2)
        count = int(values['count'])
        image = unquote(values['image'])
    except (KeyError, ValueError):
        return HttpResponse(status=400)

    if price < 0.00 or special_price < 0.00 or special_price > price or count <= 0.00:
        return HttpResponse(status=400)

    slug = name.replace(' ', '-') + get_random_string(length=4)
    Product.objects.create(name=name, description=description, price=price, special_price=special_price,
                           count=count, image=image, slug=slug, partner_id=partner.id)
    return HttpResponse(status=200)


# only for testing purposes
@csrf_exempt
@never_cache
@require_POST
def register(request):
    name = request.POST.get('name', '')
    web_site = request.POST.get('web_site', '')
    if not name or not web_site:
        return HttpResponse(status=400)

    partner = Partner(name=name, web_site=web_site)
    try:
        raw_token = get_random_string(length=16)
        partner.token = make_password(raw_token)
    except IntegrityError:
        return HttpResponse(status=400, content='Something went wrong, please try again')
    partner.save()

    return HttpResponse(status=200, content=raw_token)


@login_required()
@require_GET
def list_products(request):
    return render(request, 'shop/shop.html', context={'products': Product.objects.all()})


@login_required()
@require_GET
def get_product(request, product_id):
    product = Product.objects.filter(id=product_id).values('id', 'name', 'slug', 'description', 'price', 'count')
    if product.exists:
        return JsonResponse(product.first(), json_dumps_params={'indent': 2})
    else:
        raise Http404


@login_required()
@require_POST
def add_to_cart(request):
    product_id = request.POST.get('product_id')
    if product_id is None:
        return HttpResponse(status=400, reason='Missing parameters')

    try:
        product = Product.objects.get(id=product_id, count__gt=0)
    except Product.DoesNotExist:
        messages.warning(request, 'This product is currently out of stock')
    else:
        order, _ = Order.objects.get_or_create(customer_id=request.user, placed=False)
        cart_item, _ = CartItem.objects.get_or_create(product_id=product, order_id=order)
        cart_item.quantity += 1
        cart_item.save()
        messages.success(request, f"Successfully added {product.name} to basket")
    return redirect(reverse('shop:list_products'))


@login_required()
@require_GET
def show_basket(request, order_id=None):
    if order_id is None:
        order, _ = Order.objects.get_or_create(customer_id=request.user, placed=False)
        return redirect(reverse('shop:show_basket', kwargs={'order_id': order.id}))

    try:
        order = Order.objects.get(id=order_id, customer_id=request.user)
    except Order.DoesNotExist:
        return HttpResponse(status=403)

    price = sum(
        [cart_item.product_id.price for cart_item in order.cartitem_set.iterator() for i in range(cart_item.quantity)])
    return render(request, 'shop/basket.html',
                  context={'order': order,
                           'price': price})


@login_required()
@require_POST
def delete_from_basket(request, cart_item_id):
    try:
        cart_item = CartItem.objects.get(id=cart_item_id, order_id__placed=False)
    except CartItem.DoesNotExist:
        raise Http404

    cart_item.quantity -= 1
    cart_item.save()

    if cart_item.quantity == 0:
        cart_item.delete()

    messages.success(request, f"Successfully removed 1x '{cart_item.product_id.name}' from your basket")

    return redirect(reverse('shop:show_current_basket'))


@login_required()
@require_http_methods(['GET', 'POST'])
def checkout(request, order_id):
    try:
        order = Order.objects.get(id=order_id, customer_id=request.user, placed=False)
    except Order.DoesNotExist:
        return HttpResponse(status=403)

    if request.method == 'GET':
        return render(request, 'shop/checkout.html', context={'order': order})
    else:
        for item in order.cartitem_set.iterator():
            if item.quantity > item.product_id.count:
                messages.warning(request, f'The requested quantity of {item.product_id.name} exceeds '
                                          f'the currently available stock of {item.product_id.count}')
                return redirect(reverse('shop:show_current_basket'))

        street = request.POST.get('street', '')
        city = request.POST.get('city', '')
        zip_code = request.POST.get('zip_code', '')
        country = request.POST.get('country', '')
        info = request.POST.get('additional_info', '')
        method = request.POST.get('method', '')

        if not (street and city and zip_code and country and method and order.cartitem_set):
            return HttpResponse(status=400, reason='Missing Parameters')

        if method not in ['PayPal', 'Credit Card', 'Cash', 'Red stone of Aya']:
            return HttpResponse(status=400, reason='Illegal payment method')

        try:
            address, _ = Address.objects.get_or_create(street=street, city=city, zip_code=zip_code, country=country,
                                                       additional_info=info)
        except ValueError:
            return HttpResponse(400)

        amount = sum([cart_item.product_id.price for cart_item in order.cartitem_set.iterator() for i in
                      range(cart_item.quantity)])
        payment, _ = Payment.objects.get_or_create(method=method, amount=amount)

        order.shipping_address = address
        order.payment = payment
        order.date_placed = timezone.now().date()

        for cart_item in order.cartitem_set.iterator():
            cart_item.product_id.count -= cart_item.quantity
            cart_item.product_id.save()

        order.placed = True
        order.save()
        messages.success(request, 'Order successful')
        return redirect(reverse('shop:list_products'))

simple_ecommerce/shop/templates/shop/basket.html
{% extends 'base.html' %}
{% block content %}

    {% load static %}
    {% load colorful_style %}
    {% load shop_extras %}

    <div id="price_display" style="display:flex;align-items:center;justify-content: space-between;">
        <h1>Total price: {{ price|floatformat:2 }}€</h1>
        {% if order.placed %}
            <h1 style="float: right">(PAID at {{ order.date_placed|date:'M. d, Y' }})</h1>
        {% endif %}
        {% if price > 0 and not order.placed %}
            <a class="btn" href="{% url 'shop:checkout' request.path|slice:'13:14' %}" style="{% colorful_style %}">
                Checkout
            </a>
        {% endif %}
    </div>
    <br>
    {% for cart_item in order.cartitem_set.iterator %}
        {% with cart_item.product_id as product %}
            <div class="card">
                <div class="card-header" style="display:flex;justify-content: space-between;{% colorful_style %}">
                    ({{ cart_item.quantity }}x) {{ product.name }}
                    <i>
                        by {% if product.user is not None %}
                        {{ product.user.get_full_name }}{% elif product.partner is not None %}
                        {{ product.partner.name }}{% else %}Speedwagon Foundation{% endif %}
                    </i>
                </div>
                <div class="card-body" style="display: flex;align-items: center;text-align: center;">
                    <img src="{{ product.image }}" alt="image of {{ product.name }}"
                         style="width: 15%;border-radius: 0.5em;border: 2px solid grey"
                         onerror="this.src='{% pillar_man %}'">
                    <div style="width: 100%">{{ product.description }}</div>
                </div>
                <div class="card-footer"
                     style="{% colorful_style %};display: flex;align-items: center;justify-content: space-between">
                    <div>Price: <b>{{ cart_item.total_cost|floatformat:2 }}€</b></div>
                    {% if not order.placed %}
                        <form action="{% url 'shop:delete_from_basket' cart_item.id %}" method="post">
                            {% csrf_token %}
                            <button class="btn" style="{% colorful_style %}">Delete</button>
                        </form>
                    {% endif %}
                </div>
            </div>
            <br>
        {% endwith %}
    {% endfor %}

{% endblock %}

simple_ecommerce/shop/templates/shop/checkout.html
{% extends 'base.html' %}
{% block content %}

    {% load static %}
    {% load colorful_style %}
    <script>
        function finalize_purchase() {
            $('#inputs').toggle()
            $('#savior').toggle()
            $('#submitter').toggle()

            let address = $(document.createElement('h1'))
            address.text('Shipping Address')

            let address_info = $(document.createElement('pre'))
            address_info.text(`\n${$('#street').val()}\n${$('#city').val()}\n${$('#zip_code').val()}\n${$('#country').val()}\n${$('#additional_info').val()}\n`)

            let payment = $(document.createElement('h1'))
            payment.text('Payment Method')

            let payment_info = $(document.createElement('pre'))
            payment_info.text(`\n${$('#method').val()}`)

            $('#purchase-form').before(address)
            address.after(address_info)
            address_info.after(payment)
            payment.after(payment_info)
        }
    </script>
    <form id="purchase-form" action="{% url 'shop:checkout' order.id %}" method="post"
          onkeydown="return event.key !== 'Enter';">
        {% csrf_token %}
        <div id="inputs"
             style="display: flex;flex-direction: column;align-items: center;border-radius:0.5em;border: 1px solid grey;padding:2vh">
            <div>
                <label for="street">Street</label>
                <input id="street" name="street" value="" required>
            </div>
            <div>
                <label for="city">City</label>
                <input id="city" name="city" value="" required>
            </div>
            <div>
                <label for="zip_code">ZIP code</label>
                <input id="zip_code" name="zip_code" value="" required>
            </div>
            <div>
                <label for="country">Country</label>
                <input id="country" name="country" value="" required>
            </div>
            <div>
                <label for="additional_info">Additional info</label>
                <input id="additional_info" name="additional_info" value="">
            </div>
            <div>
                <label for="method">Payment method</label>
                <select id="method" name="method">
                    <option value="PayPal">PayPal</option>
                    <option value="Credit Card">Credit Card</option>
                    <option value="Cash">Cash</option>
                    <option value="Red stone of Aya">Red stone of Aya</option>
                </select>
            </div>
        </div>
        <button id="submitter" type="submit" class="btn" style="{% colorful_style %};display: none;">
            Submit
        </button>
    </form>
    <br>
    <button id="savior" class="btn" style="{% colorful_style %};width: 100%" onclick="finalize_purchase()">
        Save
    </button>

{% endblock %}

simple_ecommerce/shop/templates/shop/shop.html
{% extends 'base.html' %}
{% block content %}

    {% load static %}
    {% load colorful_style %}
    {% load shop_extras %}

    <script>
        function show_product_info(id) {
            window.location.href = `{% url 'shop:list_products' %}#${id}`
        }

        window.onhashchange = function () {
            let id = window.location.hash.slice(1)
            let xhr = new XMLHttpRequest()
            if (!id)
                return

            xhr.open('GET', `/shop/products/${id}/`, false)
            xhr.send()

            if (xhr.status >= 400)
                return

            let data = JSON.parse(xhr.responseText)

            Object.keys(data).forEach(function (key) {
                console.log(key)
                $(`#${key}`).text(data[key])
                $('#shop_modal').modal('toggle')
            });
            $('#product_id').val(data['id'])
        }
        window.onload = window.onhashchange
    </script>

    <div class="modal fade" id="shop_modal" tabindex="-1" role="dialog" aria-labelledby="shop_modalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Buy Product</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <u>Name:</u>
                    <div id="name"></div>
                    <u>Slug:</u>
                    <div id="slug"></div>
                    <u>Description:</u>
                    <div id="description"></div>
                    <u>Price (in €):</u>
                    <div id="price"></div>
                    <u>Still available:</u>
                    <div id="count"></div>
                </div>
                <form action="{% url 'shop:add_to_cart' %}" method="POST">
                    {% csrf_token %}
                    <div class="modal-footer">
                        <input id="product_id" name="product_id" value="" hidden>
                        <button type="submit" class="btn" style="{% colorful_style %};float: right">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    {% for product in products %}
        <div class="card" onclick="show_product_info({{ product.id }})">
            <div class="card-header" style="display:flex;justify-content: space-between;{% colorful_style %}">
                {{ product.name }}
                <i>
                    by {% if product.user is not None %}
                    {{ product.user.get_full_name }}{% elif product.partner is not None %}
                    {{ product.partner.name }}{% else %}Speedwagon Foundation{% endif %}
                </i>
            </div>
            <div class="card-body" style="display: flex;align-items: center;text-align: center">
                <img src="{{ product.image }}" alt="image of {{ product.name }}"
                     style="width:15%;border-radius: 0.5em;border: 2px solid grey"
                     onerror="this.src='{% pillar_man %}'">
                <i style="width: 100%">{{ product.description }}</i>
            </div>
        </div>
        <br>
    {% endfor %}

{% endblock %}