simple_ecommerce/shop/urls.py
from django.urls import path

from . import views

app_name = 'shop'

urlpatterns = [
    path('api/products/', views.get_many, name='get_many'),
    path('api/products/<int:product_id>/', views.fetch_or_delete, name='fetch_or_delete'),
    path('api/products/create/', views.create, name='create'),

    # only for testing purposes
    path('api/register_partner/', views.register, name='register'),

    path('shop/products/list/', views.list_products, name='list_products'),
    path('shop/products/<int:product_id>/', views.get_product, name='get_product'),
    path('shop/basket/add/', views.add_to_cart, name='add_to_cart'),
    path('shop/basket/', views.show_basket, name='show_current_basket'),
    path('shop/basket/<int:order_id>/', views.show_basket, name='show_basket'),
    path('shop/basket/delete/<int:cart_item_id>/', views.delete_from_basket, name='delete_from_basket'),
    path('shop/checkout/<int:order_id>/', views.checkout, name='checkout'),

]

simple_ecommerce/simple_ecommerce/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('', include('user_mgmt.urls')),
    path('', include('shop.urls')),
    path('', include('profile.urls'))
]

# register static files base
urlpatterns += staticfiles_urlpatterns()

simple_ecommerce/user_mgmt/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [
    path('index/', views.index, name='index'),
    path('accounts/login/', LoginView.as_view(template_name='user_mgmt/login.html'), name='login'),
    path('accounts/logout/', views.logout_view, name='logout'),
    path('accounts/registration/', views.registration_view, name='registration'),
    path('accounts/<str:email>/verify/<str:token>/', views.verify, name='verify'),

    path('accounts/password-reset/', views.password_forgotten, name='password_forgotten'),
    path('accounts/<str:email>/reset/<str:token>/', views.reset_password, name='reset_password'),

    path('accounts/tokensignin/', views.token_sign_in, name='tokensignin')
]

simple_ecommerce/user_mgmt/models.py
from django.contrib.auth.base_user import BaseUserManager
from django.contrib.auth.models import AbstractUser
from django.db.models import EmailField, CharField, DateTimeField, Model, OneToOneField, CASCADE
from django.utils import timezone
from django.utils.crypto import get_random_string
from django.utils.translation import ugettext_lazy as _


class UserManager(BaseUserManager):

    def create_user(self, username, password, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        extra_fields.setdefault('is_active', False)

        if not username:
            raise ValueError(_('username must be set'))
        username = self.normalize_email(username)
        user = self.model(username=username, **extra_fields)
        user.set_password(password)
        user.datetime_joined = timezone.now()
        user.activation_token = get_random_string(length=16)
        user.save(using=self._db)
        return user

    def create_superuser(self, username, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self.create_user(username, password, **extra_fields)


class User(AbstractUser):
    username = EmailField(_('username'), unique=True,
                          error_messages={'unique': _("A user with that username already exists.")})
    email = None

    date_joined = None

    datetime_joined = DateTimeField(_('date joined'), blank=True, null=True)

    activation_token = CharField(_('first name'), max_length=16, blank=True)

    @property
    def enabled(self):
        return self.is_active

    objects = UserManager()


class PasswordResetToken(Model):
    user = OneToOneField(User, on_delete=CASCADE)
    value = CharField(_('value'), max_length=16)

simple_ecommerce/user_mgmt/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.forms import EmailField, Form, PasswordInput, CharField
from django.utils.crypto import get_random_string
from django.utils.translation import gettext_lazy as _

from user_mgmt.models import User


class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ("username", "first_name", "last_name")

    def save(self, commit=True):
        user = super().save(commit=False)
        user.is_active = False
        user.activation_token = get_random_string(length=16)

        if commit:
            user.save()

        return user


class PasswordResetRequestForm(Form):
    username = EmailField(max_length=254)


class CustomPasswordResetForm(Form):
    password1 = CharField(label=_("Password"), max_length=32, widget=PasswordInput)
    password2 = CharField(label=_("Password confirmation"), max_length=32, widget=PasswordInput,
                          help_text='Enter the same password as before, for verification.')

simple_ecommerce/user_mgmt/views.py
from django.contrib import messages
from django.contrib.auth import login, password_validation
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import logout_then_login
from django.core.exceptions import ValidationError
from django.core.mail import send_mail
from django.http import HttpResponse, Http404
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.utils import timezone
from django.utils.crypto import get_random_string
from django.views.decorators.http import require_GET, require_POST, require_http_methods
from google.auth.transport import requests
from google.oauth2 import id_token

from user_mgmt.forms import CustomUserCreationForm, PasswordResetRequestForm, CustomPasswordResetForm
from user_mgmt.models import User, PasswordResetToken


@login_required()
@require_GET
def index(request):
    return render(request, 'user_mgmt/index.html')


@require_POST
def logout_view(request):
    if request.user.is_authenticated:
        messages.success(request, 'Logout successful')
        return logout_then_login(request)
    else:
        return HttpResponse(status=401)


@require_http_methods(['GET', 'POST'])
def registration_view(request):
    if request.method == 'GET':
        return render(request, 'user_mgmt/registration.html', {'form': CustomUserCreationForm()})
    else:
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)

            messages.success(request, f"Activation link sent to '{user.username}'")
            send_mail('Activation Link',
                      f"http://localhost:3000/accounts/{user.username}/verify/{user.activation_token}/",
                      'shop@speedwagon.foundation', [user.username])
            return redirect(reverse('accounts:index'))
        messages.warning(request, 'Registration failed')
        return render(request, 'user_mgmt/registration.html', {'form': form})


@require_GET
def verify(request, email, token):
    user = get_object_or_404(User, username=email, activation_token=token)
    if not user.is_active:
        user.is_active = True
        user.datetime_joined = timezone.now()
        user.save()
        messages.success(request, 'Account successfully activated')
        return redirect(reverse('accounts:index'))
    else:
        raise Http404


@require_http_methods(['GET', 'POST'])
def password_forgotten(request):
    if request.user.is_authenticated:
        raise Http404

    if request.method == 'GET':
        return render(request, 'user_mgmt/password_forgotten.html', {'form': PasswordResetRequestForm()})
    else:
        form = PasswordResetRequestForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            try:
                user = User.objects.get(username=username, is_active=True)
                token, _ = PasswordResetToken.objects.get_or_create(user=user)
                token.value = get_random_string(length=16)
                token.save()
                send_mail('Password reset link',
                          f"Reset your password at http://localhost:3000/accounts/{user.username}/reset/{token.value}/",
                          'shop@speedwagon.foundation', [user.username])
            except User.DoesNotExist:
                pass

            messages.success(request, f"Password reset instructions sent to '{username}'")
        return render(request, 'user_mgmt/password_forgotten.html', {'form': form})


def _is_valid_password_reset(request, password1, password2):
    if password1 == password2:
        try:
            password_validation.validate_password(password1, request.user)
        except ValidationError as error:
            messages.warning(request, '\n'.join(error))
            return False
        return True
    else:
        messages.warning(request, 'The two password fields didn’t match.')
        return False


@require_http_methods(['GET', 'POST'])
def reset_password(request, email, token):
    user = get_object_or_404(User, username=email, is_active=True)
    token = get_object_or_404(PasswordResetToken, user=user, value=token)

    if request.method == 'GET':
        return render(request, 'user_mgmt/reset.html', {'form': CustomPasswordResetForm()})
    else:
        form = CustomPasswordResetForm(request.POST, user)
        if form.is_valid() and \
                _is_valid_password_reset(request, form.cleaned_data['password1'], form.cleaned_data['password2']):
            user.set_password(form.cleaned_data['password1'])
            user.save()
            token.delete()
            messages.success(request, f"Successfully reset password for '{user.username}'")
            return redirect(reverse('accounts:login'))

        return render(request, 'user_mgmt/reset.html', {'form': form})


@require_POST
def token_sign_in(request):
    token = request.POST.get('id_token', '')
    if not token:
        return HttpResponse(status=400)
    try:
        client_id = '39346139449-nrl3aj1sc0cijkbpg4h0prtgbmb8trs1.apps.googleusercontent.com'
        idinfo = id_token.verify_oauth2_token(token, requests.Request(), client_id)
        username = idinfo['email']

        try:
            user = User.objects.get(username=username)
        except User.DoesNotExist:
            user = User.objects.create_user(username=username, password=None, first_name=idinfo['given_name'],
                                            last_name=idinfo['family_name'])
            user.is_active = True
            user.datetime_joined = timezone.now()
            user.save()

        login(request, user)
        return HttpResponse(status=200)
    except ValueError:
        return HttpResponse(status=400)

simple_ecommerce/user_mgmt/templates/user_mgmt/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="author" content="Moritz Wilhelm; Daniel Emmel">
    <title>Official Speedwagon Foundation Shop</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
          integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
            integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
            integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
            integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
            crossorigin="anonymous"></script>
    {% load colorful_style %}
    <style>
        .pillar-men {
        {% colorful_style %}
        }
    </style>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light" style="border: 1px solid black">
    <a class="navbar-brand">SFS</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            {% if not user.is_authenticated %}
                <li class="nav-item{% if 'login' in request.path %} active{% endif %}">
                    <a class="nav-link" href="{% url 'accounts:login' %}">
                        Login
                    </a>
                </li>
                <li class="nav-item {% if 'registration' in request.path %} active{% endif %}">
                    <a class="nav-link" href="{% url 'accounts:registration' %}">
                        Registration
                    </a>
                </li>
                </ul>
            {% else %}
                <li class="nav-item{% if 'index' in request.path %} active{% endif %}">
                    <a class="nav-link" href="{% url 'accounts:index' %}">
                        Home
                    </a>
                </li>
                </ul>
                <form action="{% url 'accounts:logout' %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn">Logout</button>
                </form>
            {% endif %}
    </div>
</nav>
<br>
<div class="container-fluid">
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
                {{ message|linebreaksbr }}
            </div>
        {% endfor %}
    {% endif %}
    {% block content %}
    {% endblock %}
</div>
</div>
</body>
</html>

simple_ecommerce/user_mgmt/templates/user_mgmt/index.html
{% extends 'base.html' %}
{% block content %}

    {% load colorful_style %}

    <h1>Welcome <i>{{ user.get_full_name }}</i>!</h1>

{% endblock %}

simple_ecommerce/user_mgmt/templates/user_mgmt/login.html
{% extends 'base.html' %}
{% block content %}

    {% load colorful_style %}

    <form id="login" action="{% url 'accounts:login' %}" method="POST">
        {% csrf_token %}
        <div class="form-group">
            {% if form.username.errors %}
                <div class="alert alert-danger">
                    {{ form.username.errors }}
                </div>
            {% endif %}
            {{ form.username.label_tag }}
            {{ form.username.help_text }}
            {{ form.username }}
        </div>
        <div class="form-group">
            {% if form.password.errors %}
                <div class="alert alert-danger">
                    {{ form.password.errors }}
                </div>
            {% endif %}
            {{ form.password.label_tag }}
            {{ form.password.help_text }}
            {{ form.password }}
        </div>

        {% if form.non_field_errors %}
            <div class="alert alert-danger">
                {{ form.non_field_errors }}
            </div>
        {% endif %}

        {% if request.GET.next %}
            <input type="hidden" name="next" value="{{ request.GET.next }}">
        {% endif %}

        <button type="submit" class="btn" style="{% colorful_style %}">Submit</button>
        <a class="btn" style="{% colorful_style %}" href="{% url 'accounts:password_forgotten' %}">Forgot password?</a>
    </form>

    <br>

    <div id="signin2"></div>
    <script>
        function onSignIn(googleUser) {
            let xhr = new XMLHttpRequest()
            xhr.open('POST', 'http://localhost:3000/accounts/tokensignin/', true)
            xhr.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded')

            xhr.onreadystatechange = function () {
                if (xhr.readyState === 4) {
                    if (xhr.status === 200)
                        location.href = '/index/'
                    else
                        onFailure()
                }
            }

            let id_token = googleUser.getAuthResponse().id_token
            xhr.send(`id_token=${id_token}&csrfmiddlewaretoken={{csrf_token}}`)
        }


        function onFailure() {
            let warning = $(document.createElement('div'))
            warning.addClass('alert alert-warning')
            warning.text(`Google Sign-In failed. Please try again!`)
            warning.insertBefore($("#login"))
        }

        function renderButton() {
            gapi.signin2.render('signin2', {
                'scope': 'profile email',
                'width': 240,
                'height': 50,
                'longtitle': true,
                'theme': 'dark',
                'onsuccess': onSignIn,
                'onfailure': onFailure
            });
        }
    </script>

    <script src="https://apis.google.com/js/platform.js?onload=renderButton" async defer></script>

{% endblock %}

simple_ecommerce/user_mgmt/templates/user_mgmt/otp.html
{% extends 'base.html' %}
{% block content %}

    {% load colorful_style %}

    <form action="{% url 'accounts:otp' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_username">Username:</label>
            <input type="text" name="username" autofocus autocapitalize="none" autocomplete="username" maxlength="254"
                   required id="id_username">
        </div>
        <div class="form-group">
            <label for="id_password">Password:</label>
            <input type="password" name="password" autocomplete="current-password" required id="id_password">
        </div>

        <button type="submit" class="btn" style="{% colorful_style %}">Submit</button>
    </form>

{% endblock %}

simple_ecommerce/user_mgmt/templates/user_mgmt/password_forgotten.html
{% extends 'base.html' %}
{% block content %}

    {% load colorful_style %}

    <form action="{% url 'accounts:password_forgotten' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            {% if form.username.errors %}
                <div class="alert alert-danger">
                    {{ form.username.errors }}
                </div>
            {% endif %}
            {{ form.username.label_tag }}
            {{ form.username.help_text }}
            {{ form.username }}
        </div>
        <button type="submit" class="btn" style="{% colorful_style %}">Request password reset</button>
    </form>

{% endblock %}

simple_ecommerce/user_mgmt/templates/user_mgmt/passwort_forgotten.html
{% extends 'base.html' %}
{% block content %}

    {% load colorful_style %}

    <form action="{% url 'accounts:password_forgotten' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            {% if form.username.errors %}
                <div class="alert alert-danger">
                    {{ form.username.errors }}
                </div>
            {% endif %}
            {{ form.username.label_tag }}
            {{ form.username.help_text }}
            {{ form.username }}
        </div>
        <button type="submit" class="btn" style="{% colorful_style %}">Request password reset</button>
    </form>

{% endblock %}

simple_ecommerce/user_mgmt/templates/user_mgmt/registration.html
{% extends 'base.html' %}
{% block content %}

    {% load colorful_style %}

    <form action="{% url 'accounts:registration' %}" method="POST">
        {% csrf_token %}
        <div class="fieldWrapper">
            {% if form.username.errors %}
                <div class="alert alert-danger">
                    {{ form.username.errors }}
                </div>
            {% endif %}
            {{ form.username.label_tag }}
            {{ form.username.help_text }}
            {{ form.username }}
        </div>
        <div class="fieldWrapper">
            {% if form.first_name.errors %}
                <div class="alert alert-danger">
                    {{ form.first_name.errors }}
                </div>
            {% endif %}
            {{ form.first_name.label_tag }}
            {{ form.first_name.help_text }}
            {{ form.first_name }}
        </div>
        <div class="fieldWrapper">
            {% if form.last_name.errors %}
                <div class="alert alert-danger">
                    {{ form.last_name.errors }}
                </div>
            {% endif %}
            {{ form.last_name.label_tag }}
            {{ form.last_name.help_text }}
            {{ form.last_name }}
        </div>
        <div class="fieldWrapper">
            {% if form.password1.errors %}
                <div class="alert alert-danger">
                    {{ form.password1.errors }}
                </div>
            {% endif %}
            {{ form.password1.label_tag }}
            {{ form.password1.help_text }}
            {{ form.password1 }}
        </div>
        <div class="fieldWrapper">
            {% if form.password2.errors %}
                <div class="alert alert-danger">
                    {{ form.password2.errors }}
                </div>
            {% endif %}
            {{ form.password2.label_tag }}
            {{ form.password2.help_text }}
            {{ form.password2 }}
        </div>

        {% if form.non_field_errors %}
            <div class="alert alert-danger">
                {{ form.non_field_errors }}
            </div>
        {% endif %}

        <button type="submit" class="btn" style="{% colorful_style %}">Submit</button>
    </form>

{% endblock %}

simple_ecommerce/user_mgmt/templates/user_mgmt/reset.html
{% extends 'base.html' %}
{% block content %}

    {% load colorful_style %}

    <h1>Enter your new password.</h1>
    <form action="{{ request.path }}" method="post">
        {% csrf_token %}
        <div class="fieldWrapper">
            {% if form.password1.errors %}
                <div class="alert alert-danger">
                    {{ form.password1.errors }}
                </div>
            {% endif %}
            {{ form.password1.label_tag }}
            {{ form.password1.help_text }}
            {{ form.password1 }}
        </div>
        <div class="fieldWrapper">
            {% if form.password2.errors %}
                <div class="alert alert-danger">
                    {{ form.password2.errors }}
                </div>
            {% endif %}
            {{ form.password2.label_tag }}
            {{ form.password2.help_text }}
            {{ form.password2 }}
        </div>

        {% if form.non_field_errors %}
            <div class="alert alert-danger">
                {{ form.non_field_errors }}
            </div>
        {% endif %}

        <button type="submit" class="btn" style="{% colorful_style %}">Change</button>
    </form>

{% endblock %}