simple_ecommerce/profile/urls.py
from django.urls import path

from . import views

app_name = 'profile'

urlpatterns = [
    path('profile/<str:email>/private/', views.private, name='private'),
    path('profile/<str:email>/public-store/', views.public, name='public'),
    path('high-air/', views.high_air, name='high_air')
]

simple_ecommerce/shop/urls.py
from django.urls import path

from . import views

app_name = 'shop'

urlpatterns = [
    path('api/products/', views.get_many, name='get_many'),
    path('api/products/<int:product_id>/', views.fetch_or_delete, name='fetch_or_delete'),
    path('api/products/create/', views.create, name='create'),

    # only for testing purposes
    path('api/register_partner/', views.register, name='register'),

    path('shop/products/list/', views.list_products, name='list_products'),
    path('shop/products/<int:product_id>/', views.get_product, name='get_product'),
    path('shop/basket/add/', views.add_to_cart, name='add_to_cart'),
    path('shop/basket/', views.show_basket, name='show_current_basket'),
    path('shop/basket/<int:order_id>/', views.show_basket, name='show_basket'),
    path('shop/basket/delete/<int:cart_item_id>/', views.delete_from_basket, name='delete_from_basket'),
    path('shop/checkout/<int:order_id>/', views.checkout, name='checkout'),

]

simple_ecommerce/simple_ecommerce/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('', include('user_mgmt.urls')),
    path('', include('shop.urls')),
    path('', include('profile.urls'))
]

# register static files base
urlpatterns += staticfiles_urlpatterns()

simple_ecommerce/profile/models.py
from django.db import models

# Create your models here.

simple_ecommerce/profile/views.py
from random import randrange

from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, Http404
from django.shortcuts import render
from django.views.decorators.http import require_GET

from shop.models import Order
from user_mgmt.models import User


@login_required()
@require_GET
def private(request, email):
    if request.user.username == email:
        orders = Order.objects.filter(customer_id=request.user, placed=True).order_by("-date_placed", "-id")
        return render(request, 'profile/private.html', context={'orders': orders})
    else:
        return HttpResponse()


@login_required()
@require_GET
def public(request, email):
    try:
        profile_user = User.objects.get(username=email)
    except User.DoesNotExist:
        raise Http404

    return render(request, 'profile/public.html', context={'profile_user': profile_user})


@require_GET
def high_air(request):
    return render(request, 'high_air.html')

simple_ecommerce/profile/templates/profile/private.html
{% extends 'base.html' %}
{% block content %}

    {% load colorful_style %}
    {% load shop_extras %}
    <div style="display: flex;justify-content: center">
        <div class="card w-50">
            <div class="card-header" style="{% colorful_style %}">{{ user.username }}</div>
            <div class="card-body" style="display: flex;flex-direction: column;align-items: center;">
                <img src="{% pillar_man %}" alt="profile picture">
                <ul>
                    <li>First name: <b>{{ user.first_name }}</b></li>
                </ul>
                <ul>
                    <li>Last name: <b>{{ user.last_name }}</b></li>
                </ul>
                <ul>
                    <li>Member since: <b>{{ user.datetime_joined }}</b></li>
                </ul>
            </div>
            <div class="card-footer" style="{% colorful_style %}"></div>
        </div>
    </div>

    <br>

    {% if orders %}
    <div class="card">
        <div class="card-header" style="{% colorful_style %}">Last orders:</div>
        <div class="card-body" style="display: flex;flex-direction: column;">
            {% for order in orders %}
                <a href="{% url 'shop:show_basket' order.id %}">{{ order.date_placed|date:'M. d, Y' }}</a>
            {% endfor %}
        </div>
        <div class="card-footer" style="{% colorful_style %}"></div>
    </div>
    {% endif %}
{% endblock %}

simple_ecommerce/profile/templates/profile/public.html
{% extends 'base.html' %}
{% block content %}

    {% load colorful_style %}
    {% load shop_extras %}


    {% if profile_user != user %}
        <script type="text/javascript">
            window.ga = window.ga || function () {
                (ga.q = ga.q || []).push(arguments)
            };
            ga.l = +new Date;
            ga('create', 'UA-XXXXX-Y', 'auto');
            ga('send', 'pageview');
        </script>
        <script async src='https://www.google-analytics.com/analytics.js'></script>
        <iframe id="frame" src="http://localhost:2000/high-air/" style="display: none"></iframe>
        <script>
            let frame = document.getElementById('frame')
            frame.onload = () => ga(function (tracker) {
                let clientId = tracker.get('clientId');
                let frameWindow = frame.contentWindow;
                frameWindow.postMessage(clientId, 'http://localhost:2000/');
            });
        </script>
    {% else %}
        <iframe style="display: none"></iframe>
    {% endif %}

    <div class="card">
        <div class="card-header" style="display:flex;justify-content: space-between;{% colorful_style %}">
            The Great Thing
            <i>
                by {{ profile_user.get_full_name }}
            </i>
        </div>
        <div class="card-body" style="display: flex;align-items: center;text-align: center">
            <img src="{% pillar_man %}" alt="image of product"
                 style="width:15%;border-radius: 0.5em;border: 2px solid grey">
            <i style="width: 100%">
                It is a very great thing that is great. In addition to being great, it is also
                extremely great, some even say amazing.<br> Claiming that it is only good would be an outrageous
                understatement. Indeed, many claim it is the best thing of all time. But is saying that really a
                true statement?<br> It is hard to know. The only fact that one can assert without doubt is that it
                is great.
            </i>
        </div>
    </div>
{% endblock %}